# 西瓜视频 夜神模拟器
debug: false
# 游戏名称, xigua  每日挑战 / cddh 大奖赛 / huajiao 花椒 / zscr 芝士超人
app: xigua
# 是否模拟自动答题
automatic: false
# 对应的设备类型：ios or android
device: ios
# 使用的ocr工具： baidu or tesseract
ocr: baidu
# android 连接地址
# 若为安卓真机，打开 USB 调试模式，终端输入 adb devices ，显示设备号则表示成功，如下例子：
# List of devices attached
# 6934dc33    device
# adb_address 处填入设备号
# 若为模拟器，则填入连接地址
# 夜神模拟器 127.0.0.1:62001
# 逍遥模拟器 127.0.0.1:21503
adb_address: '127.0.0.1:62001'
# ios 设备连接wda的地址
wda_address: '127.0.0.1:8100'
# 百度OCR API参数
Baidu_API_Key: XB6xqK0EWjRl7Ithmmwu2QGg
Baidu_Secret_Key: 3GwEF0PE0YDMfDwUqysqwkxIRNLUbbM7 
Baidu_token: 24.6879acb226732298d9236d28866e8b32.2592000.1527675563.282335-10683349
# 西瓜视频裁剪区域：x,y,w,h
xg_q_x: 50
xg_q_y: 400
xg_q_w: 650
xg_q_h: 250
xg_a_x: 120
xg_a_y: 650
xg_a_w: 500
xg_a_h: 580
# 冲顶大会
cd_q_x: 50
cd_q_y: 350
cd_q_w: 650
cd_q_h: 200
cd_a_x: 150
cd_a_y: 550
cd_a_w: 480
cd_a_h: 380
# 芝士超人
zs_q_x: 30
zs_q_y: 240
zs_q_w: 840
zs_q_h: 180
zs_a_x: 30
zs_a_y: 380
zs_a_w: 840
zs_a_h: 410
# 花椒直播
hj_q_x: 30
hj_q_y: 240
hj_q_w: 840
hj_q_h: 180
hj_a_x: 30
hj_a_y: 410
hj_a_w: 840
hj_a_h: 450